apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: emp-rkestg
  namespace: rkestg
  labels:
    workload.user.cattle.io/workloadselector: apps.statefulset-rkestg-emp-rkestg
spec:
  serviceName: emp
  replicas: 3
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.statefulset-rkestg-emp-rkestg
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.statefulset-rkestg-emp-rkestg
    spec:
      containers:
        - name: emp
          image: harbor.vghtpe.gov.tw/rkestg/emp:latest
          ports:
            - name: http
              containerPort: 8080        
          env:
            - name: TZ
              value: CST-8
          envFrom:
            - secretRef:
                name: datasource
          imagePullPolicy: Always
          volumeMounts:
            - name: vol-emp
              mountPath: /APData/VGHXXX
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
      volumes:
        - name: vol-emp
          nfs:
            path: /home/nfs-test
            server: 10.100.130.203
  volumeClaimTemplates: []
---
apiVersion: v1
kind: Service
metadata:
  name: emp
  namespace: rkestg
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080    
  selector:
    workload.user.cattle.io/workloadselector: apps.statefulset-rkestg-emp-rkestg
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emp
  namespace: rkestg
spec:
  rules:
    - host: rkestg.vghtpe.gov.tw
      http:
        paths:
          - path: /emp
            pathType: Prefix
            backend:
              service:
                name: emp
                port:
                  number: 8080
  tls:
    - hosts:
        - rkestg.vghtpe.gov.tw
      secretName: rkestg